name: Generate Card Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Swift
        run: |
          cd /tmp
          curl -O https://download.swift.org/swiftly/linux/swiftly-x86_64.tar.gz
          tar zxf swiftly-x86_64.tar.gz
          ./swiftly init -y --quiet-shell-followup
          echo "$HOME/.local/share/swiftly/bin" >> $GITHUB_PATH

      - name: Generate images
        run: swift test --filter testGenerateAllCardImages

      - name: Upload card images
        uses: actions/upload-artifact@v3
        with:
          name: card-images
          path: card-images/
