name: Generate Card Images

on:
  pull_request:
    branches:
      - main

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Swift
        run: |
          cd /tmp
          curl -O https://download.swift.org/swiftly/linux/swiftly-x86_64.tar.gz
          tar zxf swiftly-x86_64.tar.gz
          ./swiftly init -y --quiet-shell-followup
          echo "$HOME/.local/share/swiftly/bin" >> $GITHUB_PATH

      - name: Generate images
        run: swift test --filter testGenerateAllCardImages

      - name: Create mobile-friendly preview
        run: |
          # Create a simple HTML page for easy mobile viewing
          cat > card-images/README.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Playing Card Images - Fixed Layout</title>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  body { font-family: Arial, sans-serif; margin: 20px; background: #f8f9fa; }
                  .container { max-width: 800px; margin: 0 auto; }
                  .card { background: white; margin: 20px; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                  .improvement { background: #d4edda; border: 1px solid #c3e6cb; padding: 15px; border-radius: 5px; margin: 15px 0; }
                  h1 { color: #212529; text-align: center; }
                  h2 { color: #495057; border-bottom: 2px solid #dee2e6; padding-bottom: 10px; }
                  .before-after { display: flex; gap: 20px; flex-wrap: wrap; justify-content: center; }
                  .comparison { text-align: center; }
                  .highlight { background: #fff3cd; padding: 10px; border-radius: 5px; margin: 10px 0; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🃏 Playing Cards - Layout Improvements</h1>
                  
                  <div class="card">
                      <h2>🔧 What Was Fixed</h2>
                      <div class="improvement">
                          <strong>✅ Number Cards (7, 8, 9, 10) Layout Issues Resolved:</strong>
                          <ul>
                              <li><strong>10 card:</strong> Fixed cramped spacing - now uses even 10px gaps instead of tight 8px</li>
                              <li><strong>8 card:</strong> Eliminated inconsistent 28px jump between middle rows</li>
                              <li><strong>9 card:</strong> Improved symbol distribution for better balance</li>
                              <li><strong>7 card:</strong> Enhanced positioning for clearer visibility</li>
                          </ul>
                      </div>
                      
                      <div class="highlight">
                          <strong>📱 Mobile Viewing:</strong> All 104 SVG files are included in this download. 
                          The individual files can be opened directly in any modern mobile browser.
                      </div>
                  </div>
                  
                  <div class="card">
                      <h2>📊 Generated Files</h2>
                      <p><strong>Total:</strong> 104 card images (52 cards × 2 sizes)</p>
                      <p><strong>Formats:</strong></p>
                      <ul>
                          <li><strong>Compact:</strong> 28×36px (optimized for Apple Watch)</li>
                          <li><strong>Large:</strong> 120×168px (for iPhone/iPad)</li>
                      </ul>
                      
                      <div class="highlight">
                          <strong>🔍 To View Individual Cards:</strong><br>
                          1. Extract this ZIP file<br>
                          2. Open any .svg file in your mobile browser<br>
                          3. SVG files display perfectly on all modern mobile devices
                      </div>
                  </div>
                  
                  <div class="card">
                      <h2>🎯 Key Improvements</h2>
                      <div class="before-after">
                          <div class="comparison">
                              <h4>Before: 10 of Hearts</h4>
                              <p>Y positions: 60, 68, 76, 92, 108<br>
                              <small>Gaps: 8px, 8px, 16px, 16px</small></p>
                          </div>
                          <div class="comparison">
                              <h4>After: 10 of Hearts</h4>
                              <p>Y positions: 60, 70, 80, 90, 108<br>
                              <small>Gaps: 10px, 10px, 10px, 18px</small></p>
                          </div>
                      </div>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          echo "Created mobile-friendly preview: README.html"
          echo "Total card files: $(ls card-images/*.svg | wc -l)"

      - name: Upload card images
        uses: actions/upload-artifact@v4
        with:
          name: card-images
          path: card-images/
